'use strict';

import New from './new';

describe('New', () => {
    it('should has the same constructor', () => {
        const A = function() {};
        const origin = new A();
        const actual = New(A);
        expect(origin.constructor).toEqual(actual.constructor);
    });

    it('should has the same attributes to the object generated by original new operation', () => {
        const A = function(a, b) {
            this.a = a;
            this.b = b;
        };
        const origin = new A(1, 2);
        const actual = New(A, 1, 2);
        expect(origin.a).toEqual(actual.a);
        expect(origin.b).toEqual(actual.b);
    });

    it('should has the same prototype', () => {
        const A = function() {};
        const origin = new A();
        const actual = New(A);
        expect(origin.prototype).toEqual(actual.prototype);
    });
});
